--facil--
INSERT INTO ARMINTSA.FACILITY (MAX_BOOKING, FACILITY_NAME, FACILITY_FEE, BOOKING_DURATION_UNIT) 
	VALUES (5, 'CA_T_234', 2, 2);
INSERT INTO ARMINTSA.FACILITY (MAX_BOOKING, FACILITY_NAME, FACILITY_FEE, BOOKING_DURATION_UNIT) 
	VALUES (5, 'CA_B_232', 2, 2);
INSERT INTO ARMINTSA.FACILITY (MAX_BOOKING, FACILITY_NAME, FACILITY_FEE, BOOKING_DURATION_UNIT) 
	VALUES (5, 'CA_H_734', 2, 2);
INSERT INTO ARMINTSA.FACILITY (MAX_BOOKING, FACILITY_NAME, FACILITY_FEE, BOOKING_DURATION_UNIT) 
	VALUES (5, 'CA_K_234', 2, 2);
INSERT INTO ARMINTSA.FACILITY (MAX_BOOKING, FACILITY_NAME, FACILITY_FEE, BOOKING_DURATION_UNIT) 
	VALUES (5, 'CA_C_234', 2, 2);

INSERT INTO ARMINTSA.FACILITY (MAX_BOOKING, FACILITY_NAME, FACILITY_FEE, BOOKING_DURATION_UNIT) 
	VALUES (5, 'macbook_1', 5, 24);
INSERT INTO ARMINTSA.FACILITY (MAX_BOOKING, FACILITY_NAME, FACILITY_FEE, BOOKING_DURATION_UNIT) 
	VALUES (5, 'macbook_2', 5, 24);
INSERT INTO ARMINTSA.FACILITY (MAX_BOOKING, FACILITY_NAME, FACILITY_FEE, BOOKING_DURATION_UNIT) 
	VALUES (5, 'dell_1', 5, 24);
INSERT INTO ARMINTSA.FACILITY (MAX_BOOKING, FACILITY_NAME, FACILITY_FEE, BOOKING_DURATION_UNIT) 
	VALUES (5, 'dell_2', 5, 24);
INSERT INTO ARMINTSA.FACILITY (MAX_BOOKING, FACILITY_NAME, FACILITY_FEE, BOOKING_DURATION_UNIT) 
	VALUES (5, 'cannon_1', 5, 24);
INSERT INTO ARMINTSA.FACILITY (MAX_BOOKING, FACILITY_NAME, FACILITY_FEE, BOOKING_DURATION_UNIT) 
	VALUES (5, 'cannon_2', 5, 24);
INSERT INTO ARMINTSA.FACILITY (MAX_BOOKING, FACILITY_NAME, FACILITY_FEE, BOOKING_DURATION_UNIT) 
	VALUES (5, 'soney_1', 5, 24);
INSERT INTO ARMINTSA.FACILITY (MAX_BOOKING, FACILITY_NAME, FACILITY_FEE, BOOKING_DURATION_UNIT) 
	VALUES (5, 'phillips_1', 5, 24);

INSERT INTO ARMINTSA.FACILITY (MAX_BOOKING, FACILITY_NAME, FACILITY_FEE, BOOKING_DURATION_UNIT) 
	VALUES (5, 'segate_1', 5, 24);
INSERT INTO ARMINTSA.FACILITY (MAX_BOOKING, FACILITY_NAME, FACILITY_FEE, BOOKING_DURATION_UNIT) 
	VALUES (5, 'segate_2', 5, 24);
--equip--
INSERT INTO ARMINTSA.EQUIPMENT (FACILITY_ID, EQUIPMENT_TYPE, EQUIPMENT_BOUGHT_DATE) 
	VALUES (9, 'laptop', '2015-05-14');
INSERT INTO ARMINTSA.EQUIPMENT (FACILITY_ID, EQUIPMENT_TYPE, EQUIPMENT_BOUGHT_DATE) 
	VALUES (10, 'laptop', '2014-05-14');
INSERT INTO ARMINTSA.EQUIPMENT (FACILITY_ID, EQUIPMENT_TYPE, EQUIPMENT_BOUGHT_DATE) 
	VALUES (11, 'laptop', '2013-05-14');

INSERT INTO ARMINTSA.EQUIPMENT (FACILITY_ID, EQUIPMENT_TYPE, EQUIPMENT_BOUGHT_DATE) 
	VALUES (12, 'digital_camera', '2014-05-14');
INSERT INTO ARMINTSA.EQUIPMENT (FACILITY_ID, EQUIPMENT_TYPE, EQUIPMENT_BOUGHT_DATE) 
	VALUES (13, 'digital_camera', '2013-05-14');

INSERT INTO ARMINTSA.EQUIPMENT (FACILITY_ID, EQUIPMENT_TYPE, EQUIPMENT_BOUGHT_DATE) 
	VALUES (15, 'projector', '2014-05-14');
INSERT INTO ARMINTSA.EQUIPMENT (FACILITY_ID, EQUIPMENT_TYPE, EQUIPMENT_BOUGHT_DATE) 
	VALUES (14, 'projector', '2013-05-14');

INSERT INTO ARMINTSA.EQUIPMENT (FACILITY_ID, EQUIPMENT_TYPE, EQUIPMENT_BOUGHT_DATE) 
	VALUES (17, 'external_hard_drive', '2014-05-14');
INSERT INTO ARMINTSA.EQUIPMENT (FACILITY_ID, EQUIPMENT_TYPE, EQUIPMENT_BOUGHT_DATE) 
	VALUES (16, 'external_hard_drive', '2013-05-14');

--room
INSERT INTO ARMINTSA.ROOM (FACILITY_ID, ROOM_TYPE, ROOM_CAPACITY) 
	VALUES (2, 'lecture_theater', 150);
INSERT INTO ARMINTSA.ROOM (FACILITY_ID, ROOM_TYPE, ROOM_CAPACITY) 
	VALUES (3, 'lecture_theater', 200);

INSERT INTO ARMINTSA.ROOM (FACILITY_ID, ROOM_TYPE, ROOM_CAPACITY) 
	VALUES (4, 'computer_lab', 20);

INSERT INTO ARMINTSA.ROOM (FACILITY_ID, ROOM_TYPE, ROOM_CAPACITY) 
	VALUES (5, 'computer_lab', 16);
INSERT INTO ARMINTSA.ROOM (FACILITY_ID, ROOM_TYPE, ROOM_CAPACITY) 
	VALUES (6, 'class_room', 40);
INSERT INTO ARMINTSA.ROOM (FACILITY_ID, ROOM_TYPE, ROOM_CAPACITY) 
	VALUES (7, 'class_room', 40);