/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import controller.FBS;
import entity.*;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahas36
 */
public class Gui extends javax.swing.JFrame {

    FBS fbs;
    Administrator admin;
    Booking booking2Create;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");
    DefaultComboBoxModel roomTypeModel = new DefaultComboBoxModel();
    DefaultComboBoxModel euqipmentTypeModel = new DefaultComboBoxModel();

    /**
     * Creates new form Gui
     */
    public Gui() {
        sdf.setLenient(false);
        fbs = new FBS();
        initComponents();
        admin = null;

        homePanel.setVisible(false);
        loginPanel.setVisible(true);
        admin = null;
        panelCreateBookingInfo.setVisible(false);
        String[] typeCat = {"Room", "Equipment"};
        DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
        comboBoxModel.addElement("Room");
        comboBoxModel.addElement("Equipment");
        facility.setModel(comboBoxModel);
        roomTypeModel.addElement("lecture_theater");
        roomTypeModel.addElement("class_room");
        roomTypeModel.addElement("computer_lab");
        euqipmentTypeModel.addElement("digital_camera");
        euqipmentTypeModel.addElement("laptop");
        euqipmentTypeModel.addElement("projector");
        euqipmentTypeModel.addElement("external_hard_drive");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMemberID = new javax.swing.JTextField();
        btnValidateMemberID = new javax.swing.JButton();
        panelCreateBookingInfo = new javax.swing.JPanel();
        facility = new javax.swing.JComboBox<>();
        facilityType = new javax.swing.JComboBox<>();
        facilityName = new javax.swing.JComboBox<>();
        txtStartDate = new javax.swing.JTextField();
        txtStartTime = new javax.swing.JTextField();
        txtEndDate = new javax.swing.JTextField();
        txtEndTime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAddSB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSubBookingList = new javax.swing.JTable();
        btnRemoveBooking = new java.awt.Button();
        btnCreateBooking = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtFindMemberID = new javax.swing.JTextField();
        btnFindMember = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAllSubBooking = new javax.swing.JTable();
        btnCancelSubBooking = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtStartDate1 = new javax.swing.JTextField();
        txtStartTime1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEndDate1 = new javax.swing.JTextField();
        txtEndTime1 = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnCreateMember = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        memberType = new javax.swing.JComboBox<>();
        loginPanel = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Member ID");

        btnValidateMemberID.setText("Validate");
        btnValidateMemberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateMemberIDActionPerformed(evt);
            }
        });

        facility.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        facility.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                facilityItemStateChanged(evt);
            }
        });

        facilityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lecture_theater", "class_room", "computer_lab" }));
        facilityType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                facilityTypeItemStateChanged(evt);
            }
        });

        facilityName.setModel(new DefaultComboBoxModel<>( fbs.getAllRoomsByType("lecture_theater")));

        txtStartDate.setToolTipText("yyyy-mm-dd");

        txtStartTime.setToolTipText("hh:mm");

        txtEndDate.setToolTipText("yyyy-mm-dd");

        txtEndTime.setToolTipText("hh:mm");

        jLabel4.setText("Start Date");

        jLabel5.setText("End Date");

        btnAddSB.setText("Add");
        btnAddSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSBActionPerformed(evt);
            }
        });

        tblSubBookingList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Facility Name", "Start Date", "End Date", "Fee"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSubBookingList);

        btnRemoveBooking.setLabel("Remove");
        btnRemoveBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveBookingActionPerformed(evt);
            }
        });

        btnCreateBooking.setText("Create");
        btnCreateBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCreateBookingInfoLayout = new javax.swing.GroupLayout(panelCreateBookingInfo);
        panelCreateBookingInfo.setLayout(panelCreateBookingInfoLayout);
        panelCreateBookingInfoLayout.setHorizontalGroup(
            panelCreateBookingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateBookingInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCreateBookingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(panelCreateBookingInfoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCreateBookingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelCreateBookingInfoLayout.createSequentialGroup()
                                .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(5, 5, 5)
                                .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCreateBookingInfoLayout.createSequentialGroup()
                                .addComponent(facility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facilityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(facilityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddSB)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreateBookingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreateBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panelCreateBookingInfoLayout.setVerticalGroup(
            panelCreateBookingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateBookingInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCreateBookingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facilityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facilityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddSB))
                .addGap(18, 18, 18)
                .addGroup(panelCreateBookingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCreateBookingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addGroup(panelCreateBookingInfoLayout.createSequentialGroup()
                        .addComponent(btnRemoveBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateBooking)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelCreateBookingInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnValidateMemberID)))
                .addGap(108, 108, 108))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValidateMemberID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCreateBookingInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtMemberID.getAccessibleContext().setAccessibleName("");

        jTabbedPane2.addTab("Create Booking", jPanel2);

        jLabel6.setText("Member ID");

        btnFindMember.setText("Find");
        btnFindMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindMemberActionPerformed(evt);
            }
        });

        tblAllSubBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SubBooking ID", "Facility Name", "Start Date", "End Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAllSubBooking);

        btnCancelSubBooking.setText("Cancel");
        btnCancelSubBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelSubBookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCancelSubBooking)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtFindMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 445, Short.MAX_VALUE)
                        .addComponent(btnFindMember)
                        .addGap(120, 120, 120))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFindMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindMember))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelSubBooking)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Booking Search", jPanel3);

        jLabel7.setText("Start Date");

        txtStartDate1.setToolTipText("yyyy-mm-dd");

        txtStartTime1.setToolTipText("hh:mm");

        jLabel8.setText("End Date");

        txtEndDate1.setToolTipText("yyyy-mm-dd");

        txtEndTime1.setToolTipText("hh:mm");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Facility ID", "Facility Name", "Duration unit", "Max Booking", "Extra Info"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Room", "Equipment" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStartDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtStartTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(5, 5, 5)
                        .addComponent(txtEndDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEndTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStartDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStartTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(btnSearch)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Search Available Facilites", jPanel4);
        jPanel4.getAccessibleContext().setAccessibleName("");

        btnCreateMember.setText("Create");
        btnCreateMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMemberActionPerformed(evt);
            }
        });

        jLabel9.setText("First Name");

        jLabel10.setText("Last Name");

        jLabel11.setText("DOB");
        jLabel11.setToolTipText("yyyy-MM-dd");

        jLabel12.setText("Position");

        memberType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Staff" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDob, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                        .addComponent(memberType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnCreateMember)))
                .addContainerGap(539, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(memberType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateMember)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Create Member", jPanel1);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleDescription("");

        btnLogin.setText("login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(txtPassword))
                .addContainerGap())
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (fbs.login(txtUsername.getText(), txtPassword.getText())) {
            admin = fbs.findAdminByUsername(txtUsername.getText());
            homePanel.setVisible(true);
            loginPanel.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(this,
                    "The username or password is wrong.",
                    "Cannot login",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnValidateMemberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateMemberIDActionPerformed
        try {
            Member1 selectedMember = fbs.findMemberByID(Integer.valueOf(txtMemberID.getText()));
            txtMemberID.setText(selectedMember.getFirstName() + " " + selectedMember.getLastName());
            txtMemberID.setEnabled(false);
            btnValidateMemberID.setEnabled(false);
            panelCreateBookingInfo.setVisible(true);
            booking2Create = new Booking();
            booking2Create.setMemberId(selectedMember);
            booking2Create.setUserName(admin);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "The member id is wrong.",
                    "Cannot Find member",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnValidateMemberIDActionPerformed

    private void btnAddSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSBActionPerformed
        SubBooking sb = new SubBooking();
        try {
            sb.setStartDate(sdf.parse(txtStartDate.getText().trim() + " " + txtStartTime.getText().trim()));
            sb.setEndDate(sdf.parse(txtEndDate.getText().trim() + " " + txtEndTime.getText().trim()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "The date format should be like 2016-12-28 and time format should be like 21:22",
                    "Worng date time format ",
                    JOptionPane.ERROR_MESSAGE);
        }
        if (sb.getEndDate().compareTo(sb.getStartDate()) < 0) {
            JOptionPane.showMessageDialog(this,
                    "The date start date should be before end date",
                    "Worng date ",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (facilityName.getSelectedItem() instanceof Room) {
            sb.setFacilityId(((Room) facilityName.getSelectedItem()).getFacility());
        } else {
            sb.setFacilityId(((Equipment) facilityName.getSelectedItem()).getFacility());
        }

        sb.setSubBookingSatuts("active");
        String temp = fbs.addSubBooking(booking2Create, sb);
        if (temp.isEmpty()) {
            ((DefaultTableModel) tblSubBookingList.getModel()).addRow(new Object[]{sb.getFacilityId().getFacilityName(), sb.getStartDate(), sb.getEndDate(), sb.getFacilityId().getFacilityFee()});
        } else {
            JOptionPane.showMessageDialog(this,
                    temp,
                    "Worng date",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }


    }//GEN-LAST:event_btnAddSBActionPerformed

    private void facilityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_facilityItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (facility.getSelectedItem().equals("Room")) {
                facilityType.setModel(roomTypeModel);
            } else {
                facilityType.setModel(euqipmentTypeModel);
            }
        }
    }//GEN-LAST:event_facilityItemStateChanged

    private void facilityTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_facilityTypeItemStateChanged
        // TODO add your handling code here:
        if (facility.getSelectedItem().equals("Room")) {
            DefaultComboBoxModel<IFacility> cbm = new DefaultComboBoxModel<>(fbs.getAllRoomsByType((String) facilityType.getSelectedItem()));
            facilityName.setModel(cbm);
        } else {
            DefaultComboBoxModel<IFacility> cbm = new DefaultComboBoxModel<>(fbs.getAllEquipmentsByType((String) facilityType.getSelectedItem()));
            facilityName.setModel(cbm);
        }

    }//GEN-LAST:event_facilityTypeItemStateChanged

    private void btnRemoveBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveBookingActionPerformed
        // TODO add your handling code here:
        int row = tblSubBookingList.getSelectedRow();
        if (booking2Create.getSubBookingList().get(row).getBookingId() != null) {
            fbs.removeSubBooking(booking2Create.getSubBookingList().get(row));
        }
        booking2Create.getSubBookingList().remove(row);
        ((DefaultTableModel) tblSubBookingList.getModel()).removeRow(row);
    }//GEN-LAST:event_btnRemoveBookingActionPerformed

    private void btnCreateBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBookingActionPerformed
        // TODO add your handling code here:
        if (booking2Create.getSubBookingList() != null && !booking2Create.getSubBookingList().isEmpty()) {
            try {
                fbs.CreateBooking(booking2Create);
                booking2Create = null;
                txtEndDate.setText("");
                txtEndTime.setText("");
                txtMemberID.setText("");
                txtMemberID.setEnabled(true);
                btnValidateMemberID.setEnabled(true);
                txtStartDate.setText("");
                txtStartTime.setText("");
                jTabbedPane2.setSelectedIndex(1);
                DefaultTableModel dm = (DefaultTableModel) tblSubBookingList.getModel();
                int rowCount = dm.getRowCount();
                for (int i = rowCount - 1; i >= 0; i--) {
                    dm.removeRow(i);
                }
                panelCreateBookingInfo.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Please try again",
                        "Cannot create sub-booking",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "You should at least add 1 sub-booking",
                    "Cannot create sub-booking",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateBookingActionPerformed

    private void btnFindMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindMemberActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblAllSubBooking.getModel();
        int rowCount = dtm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }
        try {
            Member1 m = null;
            if (txtFindMemberID.getText().isEmpty()) {

            } else {
                m = fbs.findMemberByID(Integer.valueOf(txtFindMemberID.getText()));

                if (m == null) {
                    throw new Exception();
                }
            }
            List<SubBooking> allActiveSubBookingsByMember = fbs.getAllActiveSubBookingsByMember(m);

            for (SubBooking sb : allActiveSubBookingsByMember) {
                Object[] row = new Object[]{sb.getSubBookingId().toString(), sb.getFacilityId().getFacilityName(), sb.getStartDate().toString(), sb.getEndDate().toString(), sb.getSubBookingSatuts()};
                dtm.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "The member id is wrong.",
                    "Cannot find member",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFindMemberActionPerformed

    private void btnCancelSubBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelSubBookingActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = tblAllSubBooking.getSelectedRow();
            DefaultTableModel dtm = (DefaultTableModel) tblAllSubBooking.getModel();
            int subBookingID = Integer.valueOf(dtm.getValueAt(selectedRow, 0).toString());
            fbs.cancelSubBooking(subBookingID);

            dtm.removeRow(selectedRow);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Please try 2bare",
                    "Cannot cancel sub-booking",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCancelSubBookingActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        Date startdate = null;
        Date endDate = null;
        try {
            startdate = (sdf.parse(txtStartDate1.getText().trim() + " " + txtStartTime1.getText().trim()));
            endDate = (sdf.parse(txtEndDate1.getText().trim() + " " + txtEndTime1.getText().trim()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "The date format should be like 2016-12-28 and time format should be like 21:22",
                    "Worng date time format ",
                    JOptionPane.ERROR_MESSAGE);
        }
        if (endDate.compareTo(startdate) < 0) {
            JOptionPane.showMessageDialog(this,
                    "The date start date should be before end date",
                    "Worng date ",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        List<? extends IFacility> facilites;
        switch (jComboBox1.getSelectedItem().toString()) {
            case "All":
                facilites=fbs.findAllAvailableFacilitys(startdate, endDate);
                break;
            case "Room":
                facilites=fbs.findAllAvailableRooms(startdate, endDate);
                break;
            default:
                facilites=fbs.findAllAvailableEquipments(startdate, endDate);

        }
        DefaultTableModel dtm= (DefaultTableModel) jTable1.getModel();
        int rowCount = dtm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }
        for (IFacility facilite : facilites) {
            Object[] obj;
            if(facilite instanceof Facility)
            {
                Facility f=(Facility) facilite;
                obj=new Object[]{f.getFacilityId(),f.getFacilityName(),f.getBookingDurationUnit(),f.getMaxBooking(),"fee: "+f.getFacilityFee()};
            }
            else if(facilite instanceof Room)
            {
                Room r=(Room) facilite;
                obj=new Object[]{r.getFacility().getFacilityId(),r.getFacility().getFacilityName(),r.getFacility().getBookingDurationUnit(),r.getFacility().getMaxBooking(),
                    "fee: "+r.getFacility().getFacilityFee()+"\n"+" capacity: "+r.getRoomCapacity()
                };

            }
            else
            {
                 Equipment r=(Equipment) facilite;
                obj=new Object[]{r.getFacility().getFacilityId(),r.getFacility().getFacilityName(),r.getFacility().getBookingDurationUnit(),r.getFacility().getMaxBooking(),
                    "fee: "+r.getFacility().getFacilityFee()+"\n"+" capacity: "+r.getEquipmentBoughtDate()
                };
            }
            dtm.addRow(obj);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCreateMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMemberActionPerformed
        // TODO add your handling code here:
        if(txtFname.getText().isEmpty() || txtLastname.getText().isEmpty() || txtDob.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,
                    "Please fill all the fields",
                    "Validation error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Date dob = null;
        try {
            dob = (sdf.parse(txtDob.getText().trim() + " 00:00"));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,
                    "Date format is worng: yyyy-MM-dd",
                    "Validation error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        try
        {
        int id=fbs.createMember(txtFname.getText(),txtLastname.getText(),dob,memberType.getSelectedItem().toString());
        txtFname.setText("");
        txtLastname.setText("");
        txtDob.setText("");
        memberType.setSelectedItem(0);
        JOptionPane.showMessageDialog(this,
                    "Member is created with id "+id,
                    "Inserted",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(this,
                    "Please try again",
                    "Cannot insert",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnCreateMemberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSB;
    private javax.swing.JButton btnCancelSubBooking;
    private javax.swing.JButton btnCreateBooking;
    private javax.swing.JButton btnCreateMember;
    private javax.swing.JButton btnFindMember;
    private javax.swing.JButton btnLogin;
    private java.awt.Button btnRemoveBooking;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnValidateMemberID;
    private javax.swing.JComboBox<String> facility;
    private javax.swing.JComboBox<IFacility> facilityName;
    private javax.swing.JComboBox<String> facilityType;
    private javax.swing.JPanel homePanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JComboBox<String> memberType;
    private javax.swing.JPanel panelCreateBookingInfo;
    private javax.swing.JTable tblAllSubBooking;
    private javax.swing.JTable tblSubBookingList;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtEndDate1;
    private javax.swing.JTextField txtEndTime;
    private javax.swing.JTextField txtEndTime1;
    private javax.swing.JTextField txtFindMemberID;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtMemberID;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtStartDate1;
    private javax.swing.JTextField txtStartTime;
    private javax.swing.JTextField txtStartTime1;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
